# Generated by Django 4.2.2 on 2023-06-08 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail adress')),
                ('dev_role', models.CharField(choices=[('Fullstack', 'Fullstack'), ('Front-end', 'Front-end'), ('Back-end', 'Back-end')], max_length=9, verbose_name='Developer Role')),
                ('github', models.URLField(verbose_name='Github profile')),
                ('whatsapp', models.CharField(max_length=31, verbose_name='Whatsapp number with area code')),
                ('linkedin', models.URLField(verbose_name='LinkedIn profile')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workplace', models.CharField(verbose_name='Place on that Role')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('timeInMonths', models.IntegerField(verbose_name='Time spent in months')),
                ('description', models.TextField(verbose_name='Description')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.work', verbose_name='Job for the role')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(verbose_name='URL')),
                ('repository', models.URLField(verbose_name='Github/Bitbucket Repository')),
                ('frontendTool', models.CharField(max_length=255, verbose_name='Front end tool used')),
                ('backendTool', models.CharField(max_length=255, verbose_name='Back end tool used')),
                ('database', models.CharField(max_length=255, verbose_name='Database used')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Author')),
            ],
        ),
    ]
