# Generated by Django 4.2.2 on 2023-06-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_role_work_alter_work_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='whatsapp',
            field=models.CharField(verbose_name='Whatsapp number with area code'),
        ),
    ]
