# Generated by Django 4.2.2 on 2023-06-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='whatsapp',
            field=models.CharField(max_length=15, verbose_name='Whatsapp number with area code'),
        ),
    ]
